name: Update Commit History

on:
  push:
    branches:
      - main
      - master
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

jobs:
  refresh:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      GOOGLE_DOC_ID: ${{ secrets.GOOGLE_DOC_ID }}
      GOOGLE_SERVICE_ACCOUNT_JSON: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Generate commit history doc
        run: python3 scripts/generate_commit_history.py

      - name: Install Google API client
        if: env.GOOGLE_DOC_ID != '' && env.GOOGLE_SERVICE_ACCOUNT_JSON != ''
        run: |
          python3 -m pip install --upgrade pip
          pip install google-api-python-client google-auth-httplib2

      - name: Push commit history to Google Docs
        if: env.GOOGLE_DOC_ID != '' && env.GOOGLE_SERVICE_ACCOUNT_JSON != ''
        run: python3 scripts/push_to_google_docs.py

      - name: Commit and push if changed
        run: |
          if git diff --quiet docs/commit-history.md; then
            echo "No documentation updates needed."
          else
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add docs/commit-history.md
            git commit -m "Update commit history documentation"
            git push
          fi
